
// /api/v1/auth/register endpoint

# @name Register new user
POST {{BaseUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "username": "hector1111",
  "email": "hector@example.com",
  "password": "Isadj12312kgsf!sda"
}

###

# @name Register using wrong parameters
POST {{BaseUrl}}/api/v1/auth/register
Content-Type: application/json

{
  "username": "hector22",
  "email": "aaa",
  "password": "bbb"
}

###

// /api/v1/auth/login endpoint

# @name Log in
POST {{BaseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "hector@example.com",
  "password": "Isadj12312kgsf!sda"
}

###

# @name Log in using wrong parameters
POST {{BaseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "aaaa",
  "password": "bbbb"
}

###

// /api/v1/auth/verify-email endpoint

# @name Verify email for user
< {%
    request.variables.set("emailVerificationToken", "Kg5QgI4jC6eFSGDCqkxceGYN94odudG2PmCjIDVWFweOrdTSWzj8gyKhOmtkkqCn")
%}
GET {{BaseUrl}}/api/v1/auth/verify-email/{{emailVerificationToken}}

###

# @name Verify email with wrong parameters
GET {{BaseUrl}}/api/v1/auth/verify-email/aaa

###

// /api/v1/auth/verify-email/resend endpoint

# @name Resend verification email for user
POST {{BaseUrl}}/api/v1/auth/verify-email/resend
Content-Type: application/json

{
  "email": "hector@example.com"
}

###

# @name Resend verification email with wrong parameters
POST {{BaseUrl}}/api/v1/auth/verify-email/resend
Content-Type: application/json

{
  "email": "aaaa"
}

###

// /api/v1/auth/refresh endpoint

# @name Refresh token
POST {{BaseUrl}}/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "fceed92eae294b8d99ccb110744d3f59"
}

###

# @name Refresh token with wrong parameters
POST {{BaseUrl}}/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "aaaa"
}

###

// /api/v1/auth/logout endpoint

# @name Log out
POST {{BaseUrl}}/api/v1/auth/logout
Content-Type: application/json

{
  "refreshToken": "fceed92eae294b8d99ccb110744d3f59"
}

###

# @name Log out with wrong parameters
POST {{BaseUrl}}/api/v1/auth/logout
Content-Type: application/json

{
  "refreshToken": "aaaa"
}

###
