---
spring:
  application:
    name: "familymoney"
  main:
    banner-mode: false
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: "org.postgresql.Driver"
  config:
    import: "optional:file:.env[.properties]"
  mail:
    host: "${MAIL_SENDER_HOST}"
    port: "${MAIL_SENDER_PORT}"
    username: "${MAIL_SENDER_USERNAME}"
    password: "${MAIL_SENDER_PASSWORD}"
    properties:
      mail:
        transport:
          protocol: "${MAIL_SENDER_PROTOCOL}"
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: "${APP_PORT}"
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %level | %msg%n"
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
springdoc:
  swagger-ui:
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
  show-actuator: true
  cache:
    disabled: true
familymoney:
  jwt:
    key: "${JWT_KEY}"
    access-token-duration: "5m"
    refresh-token-duration: "7d"
  email-verification:
    token-duration: "24h"
    wait-time: "2m"
  group-invitation:
    invitation-duration: "1h"
    max-num-invitations: 5
  reset-password:
    token-duration: "1h"
    wait-time: "2m"
    reset-url: "${RESET_PASSWORD_URL:https://miticketdecomida.com/reset-password}"
  mail:
    sender:
      email: "${MAIL_SENDER_FROM_EMAIL}"
      name: "${MAIL_SENDER_FROM_NAME}"
  admin:
    username: "${ADMIN_USERNAME}"
    email: "${ADMIN_EMAIL}"
    password: "${ADMIN_PASSWORD}"
