[versions]
springboot = "4.0.0"
springboot-dependencymanagement = "1.1.7"
springdoc-openapi = "2.8.14"
jjwt = "0.13.0"
testcontainers = "2.0.2"
mapstruct = "1.6.3"
moneta = "1.4.5"
assertj = "3.27.6"

[libraries]
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
lombok = { module = "org.projectlombok:lombok" }
springdoc-openapi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc-openapi" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }
moneta = { module = "org.javamoney:moneta", version.ref = "moneta" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }

[plugins]
springboot = { id = "org.springframework.boot", version.ref = "springboot" }
springboot-dependencymanagement = { id = "io.spring.dependency-management", version.ref = "springboot-dependencymanagement" }

[bundles]
