[versions]
springboot = "4.0.2"
springboot-dependencymanagement = "1.1.7"
springdoc-openapi = "2.8.14"
jjwt = "0.13.0"
testcontainers = "2.0.2"
moneta = "1.4.5"
assertj = "3.27.7"
jooq-plugin = "8.0.11"
lombok-plugin = "9.2.0"
thymeleafextras-springsecurity6 = "3.1.3.RELEASE"
integrationtest = "2.2.5"
uuid-creator = "6.1.1"

[libraries]
#Spring dependencies
spring-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-starter-data-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc" }
spring-starter-mail = { module = "org.springframework.boot:spring-boot-starter-mail" }
spring-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf" }
spring-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-starter-jooq = { module = "org.springframework.boot:spring-boot-starter-jooq" }
spring-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
spring-starter-flyway-test = { module = "org.springframework.boot:spring-boot-starter-flyway-test" }
spring-starter-jooq-test = { module = "org.springframework.boot:spring-boot-starter-jooq-test" }
spring-resttestclient = { module = "org.springframework.boot:spring-boot-resttestclient" }
spring-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }

# Third party dependencies
thymeleafextras-springsecurity6 = { module = "org.thymeleaf.extras:thymeleaf-extras-springsecurity6", version.ref = "thymeleafextras-springsecurity6" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
springdoc-openapi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc-openapi" }
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
moneta = { module = "org.javamoney:moneta", version.ref = "moneta" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
uuidcreator = { module = "com.github.f4b6a3:uuid-creator", version.ref = "uuid-creator" }

[plugins]
springboot = { id = "org.springframework.boot", version.ref = "springboot" }
springboot-dependencymanagement = { id = "io.spring.dependency-management", version.ref = "springboot-dependencymanagement" }
jooq = { id = "dev.monosoul.jooq-docker", version.ref = "jooq-plugin" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok-plugin" }
integrationtest = { id = "com.coditory.integration-test", version.ref = "integrationtest" }

[bundles]
