package com.familymoney.utils;

import com.familymoney.types.EmailVerificationToken;
import org.apache.commons.lang3.RandomStringUtils;

/**
 * Utility class for generating fake data for testing purposes. All the data generated by this class
 * is valid.
 */
public final class FakeGenerator {

  private static final String LOWER_CHARACTERS = "abcdefghijklmnopqrstuvwxyz";
  private static final String UPPER_CHARACTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  private static final String NUMBER_CHARACTERS = "0123456789";
  private static final RandomStringUtils random = RandomStringUtils.insecure();

  public static String username() {
    return random.next(10, LOWER_CHARACTERS);
  }

  public static String email() {
    return random.next(12, LOWER_CHARACTERS) + "@gmail.com";
  }

  public static String password() {
    return random.next(12, UPPER_CHARACTERS)
        + random.next(4, LOWER_CHARACTERS)
        + random.next(4, NUMBER_CHARACTERS)
        + "!";
  }

  public static String accessToken() {
    return "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30";
  }

  public static String refreshToken() {
    return random.next(12, UPPER_CHARACTERS)
        + random.next(10, LOWER_CHARACTERS)
        + random.next(10, NUMBER_CHARACTERS);
  }

  public static String emailVerificationToken() {
    return EmailVerificationToken.generate().toString();
  }
}
